# Generated by Django 4.0.1 on 2022-05-18 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CertificatesCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Sertifikatlar kategoriyasi')),
                ('date', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Certificates Categories',
                'verbose_name_plural': 'Certificates Categories',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Cities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'City',
                'verbose_name_plural': 'Cities',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='images/post/')),
                ('text', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='Tovar nomi')),
                ('show', models.BooleanField(default=True)),
                ('img', models.ImageField(upload_to='images/products/', verbose_name='Tovar rasmi')),
                ('date', models.DateField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ProductCategory1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Mahsulot bosh kategoriyasi')),
                ('short', models.CharField(max_length=100, verbose_name='Qisqa nomi')),
                ('imgon', models.ImageField(upload_to='images/product categories/', verbose_name='Mahsulot rasmi #1')),
                ('imgunder', models.ImageField(upload_to='images/product categories/', verbose_name='Mahsulot rasmi #2')),
                ('imgmobile', models.ImageField(upload_to='images/product categories/', verbose_name="Mahsulot rasmi telefo'nda")),
                ('date', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Product Category1',
                'verbose_name_plural': 'Product Categories1',
            },
        ),
        migrations.CreateModel(
            name='ProductCategory2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Sertifikatlar kategoriyasi')),
                ('date', models.DateField(auto_now_add=True)),
                ('bind', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.productcategory1')),
            ],
            options={
                'verbose_name': 'Product Categories2',
                'verbose_name_plural': 'Product Categories2',
            },
        ),
        migrations.CreateModel(
            name='ProductProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='Tovar qiymati nomi')),
                ('value', models.CharField(max_length=100, verbose_name='*')),
                ('bind', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.product')),
            ],
            options={
                'verbose_name': 'Product property',
                'verbose_name_plural': 'Product properties',
            },
        ),
        migrations.CreateModel(
            name='ProductCategory3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Sertifikatlar kategoriyasi')),
                ('date', models.DateField(auto_now_add=True)),
                ('bind', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.productcategory2')),
            ],
            options={
                'verbose_name': 'Product Categories3',
                'verbose_name_plural': 'Product Categories3',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='bind',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.productcategory3'),
        ),
        migrations.CreateModel(
            name='CategoryFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/documents/', verbose_name='Fayl rasmi')),
                ('file', models.FileField(upload_to='files/documents/', verbose_name='Fayl')),
                ('name', models.CharField(max_length=150, verbose_name='Fayl nomi')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('bind', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.certificatescategories')),
            ],
            options={
                'verbose_name': 'Category Files',
                'verbose_name_plural': 'Category Files',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('number', models.PositiveIntegerField()),
                ('date', models.DateField(auto_now_add=True)),
                ('email', models.CharField(blank=True, max_length=100)),
                ('message', models.TextField()),
                ('done', models.BooleanField(default=False)),
                ('bind', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.productcategory1')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.cities')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
